// Code generated by goctl. DO NOT EDIT.
package types

type ConvertReq struct {
	LongUrl string `json:"longUrl" validate:"required,longUrl"`
}

type ConvertResp struct {
	ShortUrl string `json:"shortUrl"`
}

type RedirectReq struct {
	RedReq string `path:"redirectReq" validata:"required,shortUrl"`
}

type RedirectResp struct {
	RedResp string
}

type ShowReq struct {
	ShortUrl string `path:"shortUrl" validate:"required,shortUrl"`
}

type ShowResp struct {
	LongUrl string `json:"longUrl"`
}
