// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Project/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/convert",
				Handler: ConvertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/redirect/:redirectReq",
				Handler: RedirectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/show/:shortUrl",
				Handler: ShowUrlHandler(serverCtx),
			},
		},
	)
}
